name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  - pandas
  - matplotlib
  - iris
  - xarray
  - cartopy
  - trackpy
  - pip
  - pip:
     - "--editable=git+https://github.com/tobac-project/tobac.git@RC_v1.5.0#egg=tobac"
