name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  - pandas
  - matplotlib
  - iris
  - xarray
  - cartopy
  - trackpy
  - pip:
     - "--editable=https://github.com/tobac-project/tobac/tree/RC_v1.5.0"
